### ISSUE TITLE
ModuleNotFoundError: No module named 'validators'

### ISSUE THREAD

**Issue by SyrupBoy76** [HLVM04/Tesla-Beat-Saber-Light-Show-Converter#4] opened 2022-07-05 16:53 UTC
When running the following command:

`python3 main.py https://eu.cdn.beatsaver.com/103d39b43966277c5e4167ab086f404e0943891f.zip`

I receive the following result:

`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import validators`

**Comment by HLVM04** [comment] 2022-07-05 16:57
This error is caused by a missing dependency.
Can be fixed by installing all requirements using this command: 
`pip install -r requirements.txt`

Seems like I've forgotten to mention this in the instructions, I'll update it momentarily

**Comment by SyrupBoy76** [comment] 2022-07-05 16:58
It works!  Thanks!

**Closed as completed** 2022-07-05 17:00 UTC
